services:
  as:
    build: ./AS
    container_name: as
    ports:
      - "53333:53333/udp"
    networks:
      - labnet

  fs:
    build: ./FS
    container_name: fs
    depends_on:
      - as
    environment:
      HOSTNAME: fibonacci.com
      FS_IP: fs
      AS_IP: as
      AS_PORT: 53333
    ports:
      - "9090:9090"
    networks:
      - labnet

  us:
    build: ./US
    container_name: us
    depends_on:
      - as
      - fs
    ports:
      - "8080:8080"
    networks:
      - labnet

networks:
  labnet:
    driver: bridge
